apiVersion: v1
kind: ServiceAccount
metadata:
  name: dockerhub-source-controller
  namespace: knative-sources
  labels:
    contrib.eventing.knative.dev/release: devel

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dockerhub-source-webhook
  namespace: knative-sources
  labels:
    contrib.eventing.knative.dev/release: devel
