apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-source-controller
  namespace: knative-samples
  labels:
    samples.knative.dev/release: devel

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-source-webhook
  namespace: knative-samples
  labels:
    samples.knative.dev/release: devel
