apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sample-source-controller-rolebinding
  labels:
    samples.knative.dev/release: devel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sample-source-controller
subjects:
- kind: ServiceAccount
  name: sample-source-controller
  namespace: knative-samples

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sample-source-webhook-rolebinding
  labels:
    samples.knative.dev/release: devel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sample-source-webhook
subjects:
  - kind: ServiceAccount
    name: sample-source-webhook
    namespace: knative-samples

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sample-source-controller-addressable-resolver
  labels:
    samples.knative.dev/release: devel
subjects:
- kind: ServiceAccount
  name: sample-source-controller
  namespace: knative-samples
# An aggregated ClusterRole for all Addressable CRDs.
# Ref: https://knative.dev/eventing/blob/master/config/200-addressable-resolvers-clusterrole.yaml
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: addressable-resolver
