apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerhub-source-controller
  namespace: knative-sources
  labels:
    contrib.eventing.knative.dev/release: devel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockerhub-source-controller
  template:
    metadata:
      labels:
        app: dockerhub-source-controller
        contrib.eventing.knative.dev/release: devel
    spec:
      serviceAccountName: dockerhub-source-controller

      containers:
      - name: controller
        terminationMessagePolicy: FallbackToLogsOnError
        image: ko://github.com/tom24d/eventing-dockerhub/cmd/controller

        resources:
          requests:
            cpu: 100m
            memory: 100Mi

        env:
          - name: SYSTEM_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CONFIG_LOGGING_NAME
            value: config-logging
          - name: CONFIG_OBSERVABILITY_NAME
            value: config-observability
          - name: METRICS_DOMAIN
            value: knative.dev/sources
          - name: SAMPLE_SOURCE_RA_IMAGE
            value: ko://github.com/tom24d/eventing-dockerhub/cmd/receive_adapter

        securityContext:
          allowPrivilegeEscalation: false

        ports:
          - name: metrics
            containerPort: 9090
