apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: defaulting.webhook.dockerhub.sources.knative.dev
  labels:
    contrib.eventing.knative.dev/release: devel
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: dockerhub-source-webhook
        namespace: knative-sources
    failurePolicy: Fail
    name: defaulting.webhook.dockerhub.sources.knative.dev
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.webhook.dockerhub.sources.knative.dev
  labels:
    contrib.eventing.knative.dev/release: devel
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: dockerhub-source-webhook
        namespace: knative-sources
    failurePolicy: Fail
    name: validation.webhook.knative-samples.knative.dev
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: config.webhook.dockerhub.sources.knative.dev
  labels:
    contrib.eventing..knative.dev/release: devel
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: dockerhub-source-webhook
        namespace: knative-sources
    failurePolicy: Fail
    name: config.webhook.dockerhub.sources.knative.dev
    namespaceSelector:
      matchExpressions:
        - key: contrib.eventing.knative.dev/release
          operator: Exists
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-certs
  namespace: knative-sources
  labels:
    contrib.eventing.knative.dev/release: devel
# The data is populated at install time.
