apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: defaulting.webhook.knative-samples.knative.dev
  labels:
    samples.knative.dev/release: devel
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: sample-source-webhook
        namespace: knative-samples
    failurePolicy: Fail
    name: defaulting.webhook.knative-samples.knative.dev
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.webhook.knative-samples.knative.dev
  labels:
    samples.knative.dev/release: devel
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: sample-source-webhook
        namespace: knative-samples
    failurePolicy: Fail
    name: validation.webhook.knative-samples.knative.dev
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: config.webhook.knative-samples.knative.dev
  labels:
    serving.knative.dev/release: devel
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        name: sample-source-webhook
        namespace: knative-samples
    failurePolicy: Fail
    name: config.webhook.knative-samples.knative.dev
    namespaceSelector:
      matchExpressions:
        - key: samples.knative.dev/release
          operator: Exists
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-certs
  namespace: knative-samples
  labels:
    samples.knative.dev/release: devel
# The data is populated at install time.
