apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-source-controller
  namespace: knative-samples
  labels:
    samples.knative.dev/release: devel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-source-controller
  template:
    metadata:
      labels:
        app: sample-source-controller
        samples.knative.dev/release: devel
    spec:
      serviceAccountName: sample-source-controller

      containers:
      - name: controller
        terminationMessagePolicy: FallbackToLogsOnError
        image: ko://knative.dev/sample-source/cmd/controller

        resources:
          requests:
            cpu: 100m
            memory: 100Mi

        env:
          - name: SYSTEM_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CONFIG_LOGGING_NAME
            value: config-logging
          - name: CONFIG_OBSERVABILITY_NAME
            value: config-observability
          - name: METRICS_DOMAIN
            value: knative.dev/sources
          - name: SAMPLE_SOURCE_RA_IMAGE
            value: ko://knative.dev/sample-source/cmd/receive_adapter

        securityContext:
          allowPrivilegeEscalation: false

        ports:
          - name: metrics
            containerPort: 9090
